version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=mysql-db
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_NAME=usuariosdb
    depends_on:
      - mysql-db

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'  # El puerto React
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend

  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=usuariosdb
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

volumes:
  mysql-data:
